# -*- coding: utf-8 -*-
"""MID AMELIA CONTESA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CX6gvSWup0WY969-sdexenXQnM36Xda-

1. IMPORT DAN SETUP
"""

from google.colab import drive
drive.mount('/content/drive')

DATASET_PATH = '/content/drive/MyDrive/dataset/dataset'

"""2. Load Dataset"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator

IMG_SIZE = (128,128)
BATCH = 32

train_datagen = ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True,
    rotation_range=10
)

val_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    DATASET_PATH + '/train',
    target_size=IMG_SIZE,
    batch_size=BATCH,
    class_mode='categorical'
)

val_generator = val_datagen.flow_from_directory(
    DATASET_PATH + '/test',
    target_size=IMG_SIZE,
    batch_size=BATCH,
    class_mode='categorical'
)

num_classes = train_generator.num_classes
print("Jumlah kelas:", num_classes)

num_classes = 6

"""3. MODEL CNN SEDERHANA (SEBELUM OPTIMASI)"""

# ======================
# IMPORT
# ======================
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

# ======================
# PATH DATASET (SESUAIKAN)
# ======================
train_dir = DATASET_PATH + "/train"
val_dir   = DATASET_PATH + "/test"

IMG_SIZE = (128,128)
BATCH_SIZE = 32

# ======================
# DATA GENERATOR
# ======================
train_gen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

val_gen = ImageDataGenerator(rescale=1./255)

train_data = train_gen.flow_from_directory(
    train_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical'
)

val_data = val_gen.flow_from_directory(
    val_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical'
)

# ======================
# MODEL CNN (BERSIH & STABIL)
# ======================
model = models.Sequential([
    layers.Input(shape=(128,128,3)),

    layers.Conv2D(32,3,activation='relu'),
    layers.MaxPooling2D(),

    layers.Conv2D(64,3,activation='relu'),
    layers.MaxPooling2D(),

    layers.Conv2D(128,3,activation='relu'),
    layers.MaxPooling2D(),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),

    layers.Dense(train_data.num_classes, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

# ======================
# TRAINING
# ======================
history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=10
)

# ======================
# SAVE MODEL
# ======================
model.save("model_cnn.h5")

# ======================
# GRAFIK ACCURACY
# ======================
plt.figure()
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Grafik Accuracy CNN')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

# ======================
# GRAFIK LOSS
# ======================
plt.figure()
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Grafik Loss CNN')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()

import tensorflow as tf

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=2,
    restore_best_weights=True
)

reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.3,
    patience=1,
    min_lr=1e-6
)

from PIL import Image
import os

def clean_dataset(folder):
    for root, dirs, files in os.walk(folder):
        for file in files:
            path = os.path.join(root, file)
            try:
                img = Image.open(path)
                img.verify()  # cek validitas
            except:
                print("Hapus file rusak:", path)
                os.remove(path)

# jalankan
clean_dataset('/content/drive/MyDrive/dataset/dataset/train')
clean_dataset('/content/drive/MyDrive/dataset/dataset/test')

"""5. MODEL 2 — Build MobileNetV2 (TRANSFER LEARNING)"""

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.applications import MobileNetV2

base_model = MobileNetV2(
    input_shape=(128,128,3),
    include_top=False,
    weights='imagenet'
)

# freeze biar cepat
base_model.trainable = False

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(num_classes, activation='softmax')
])

"""6. compile"""

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

"""7. GRAFIK"""

history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=10
)

"""8. Fine-Tuning RINGAN"""

for layer in base_model.layers[-20:]:
    layer.trainable = True

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history_ft = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=3
)

"""8. evaluasi"""

loss, acc = model.evaluate(val_generator)
print("Accuracy:", acc)

"""9. grafik"""

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'], label='Train')
plt.plot(history.history['val_accuracy'], label='Validation')

plt.title('Accuracy MobileNet')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

"""10.simpan model"""

import tensorflow as tf
from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Input(shape=(128,128,3)),
    layers.Conv2D(32,3,activation='relu'),
    layers.MaxPooling2D(),
    layers.Conv2D(64,3,activation='relu'),
    layers.MaxPooling2D(),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(6, activation='softmax')
])

import tensorflow as tf
from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Input(shape=(128,128,3)),
    layers.Conv2D(32,3,activation='relu'),
    layers.MaxPooling2D(),
    layers.Conv2D(64,3,activation='relu'),
    layers.MaxPooling2D(),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(6, activation='softmax')
])

model.save("model_baru.h5")

import os
print(os.listdir())

from google.colab import files
files.download("model_baru.h5")

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(train_generator, epochs=2)

model.save("model_baru.h5")

from google.colab import files
files.download("model_baru.h5")

"""11.simpan label"""

import json

with open('/content/drive/MyDrive/class_indices.json', 'w') as f:
    json.dump(train_generator.class_indices, f)

import json

with open('/content/drive/MyDrive/class_indices.json', 'w') as f:
    json.dump(train_generator.class_indices, f)

print("✅ class_indices.json berhasil dibuat")

from google.colab import files
files.download('/content/drive/MyDrive/class_indices.json')

!pip install streamlit

"""Streamlit (app.py)"""

import streamlit as st
import numpy as np
import tensorflow as tf
from PIL import Image
import json
import os

# ================================
# CONFIG
# ================================
MODEL_PATH = "model_mobilenet.keras"
LABEL_PATH = "class_indices.json"
IMG_SIZE = (128,128)

# ================================
# LOAD MODEL (AMAN)
# ================================
@st.cache_resource
def load_model_safe():
    if not os.path.exists(MODEL_PATH):
        st.error("❌ Model tidak ditemukan!")
        return None
    return tf.keras.models.load_model(MODEL_PATH)

model = load_model_safe()

# ================================
# LOAD LABEL (AMAN)
# ================================
def load_labels_safe():
    if not os.path.exists(LABEL_PATH):
        st.error("❌ class_indices.json tidak ditemukan!")
        return None
    with open(LABEL_PATH, "r") as f:
        return json.load(f)

class_idx = load_labels_safe()

if class_idx:
    idx_to_class = {v:k for k,v in class_idx.items()}
else:
    idx_to_class = None

# ================================
# UI
# ================================
st.title("🍎 Klasifikasi Buah (MobileNetV2)")
st.write("Upload gambar buah untuk diprediksi")

uploaded_file = st.file_uploader("Upload gambar", type=["jpg","jpeg","png"])

# ================================
# PREDIKSI
# ================================
if uploaded_file is not None and model is not None and idx_to_class is not None:
    try:
        # tampilkan gambar
        image = Image.open(uploaded_file).convert("RGB")
        st.image(image, caption="Gambar yang diupload", use_container_width=True)

        # preprocessing
        img = image.resize(IMG_SIZE)
        img_array = np.array(img) / 255.0
        img_array = np.expand_dims(img_array, axis=0)

        # prediksi
        preds = model.predict(img_array)[0]

        # top 3
        top3 = preds.argsort()[-3:][::-1]

        st.subheader("📊 Hasil Prediksi:")

        for i in top3:
            st.write(f"{idx_to_class[i]} : {preds[i]*100:.2f}%")

        st.success("✅ Prediksi berhasil!")

    except Exception as e:
        st.error(f"Terjadi error saat prediksi: {e}")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import numpy as np
# import tensorflow as tf
# from PIL import Image
# import json
# 
# model = tf.keras.models.load_model("/content/drive/MyDrive/model_mobilenet.keras")
# 
# with open("/content/drive/MyDrive/class_indices.json","r") as f:
#     class_idx = json.load(f)
# 
# idx_to_class = {v:k for k,v in class_idx.items()}
# 
# st.title("Klasifikasi Buah (MobileNetV2)")
# 
# file = st.file_uploader("Upload gambar", type=["jpg","png","jpeg"])
# 
# if file:
#     img = Image.open(file).convert("RGB")
#     st.image(img, caption="Gambar", use_container_width=True)
# 
#     img = img.resize((128,128))
#     x = np.array(img)/255.0
#     x = np.expand_dims(x, axis=0)
# 
#     preds = model.predict(x)[0]
#     top3 = preds.argsort()[-3:][::-1]
# 
#     st.subheader("Top-3 Prediction:")
#     for i in top3:
#         st.write(f"{idx_to_class[i]} : {preds[i]*100:.2f}%")
# 
# !streamlit run app.py